# Generated by Django 4.2.5 on 2023-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_alumno', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
